### ISSUE TITLE
Do you have an example of the server side?

### ISSUE THREAD

**Issue by nzfarmer1** [dgiannakop/Arduino-CoAP#5]
Nice library.

I have encapsulated xbee API in a library to provide reliable windowed/acked data stream that inherits from the Streams library.

Am interested to port your work to this.

However, I wondered if you had an example of the server side - i.e. in nodejs perhaps?

**Comment by dgiannakop** [comment]
Well, this is something quite old, but when we were working on this we had a java server, which can be found here: https://github.com/Uberdust/testbedListener mainly in the trxbeecoap branch.

It's been 3 years since I touched any of these and now CoAP is a finished standard, but I don't have anymore devices to develop.

**Comment by nzfarmer1** [comment]
Thanks
